project_id = "zwgjnynnbxiomtnnvztt"

[functions.analyze-text]
verify_jwt = true

[functions.analyze-text-v2]
verify_jwt = true

[functions.backup]
verify_jwt = true

[functions.cache]
verify_jwt = true

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = true

[functions.external-api]
verify_jwt = true

[functions.integrations]
verify_jwt = true

[functions.notifications]
verify_jwt = false

[functions.process-document]
verify_jwt = false

[functions.search-knowledge]
verify_jwt = true

[functions.audit-logs]
verify_jwt = true

[functions.healthz]
verify_jwt = false

[functions.admin-logs]
verify_jwt = true